// GENERATED CODE – DO NOT EDIT!

package v5

import custom "github.com/jonasrothmann/go-fhir-client/custom"

// http://hl7.org/fhir/StructureDefinition/SubscriptionTopic
type SubscriptionTopic struct {
	// Logical id of this artifact
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Metadata about the resource
	Meta *Meta `bson:"meta,omitempty" json:"meta,omitempty"`
	// A set of rules under which this content was created
	ImplicitRules *custom.URI `bson:"implicitRules,omitempty" json:"implicitRules,omitempty"`
	// Language of the resource content
	Language *custom.Code `bson:"language,omitempty" json:"language,omitempty"`
	// Text summary of the resource, for human interpretation
	Text *Narrative `bson:"text,omitempty" json:"text,omitempty"`
	// Contained, inline Resources
	Contained []Resource `bson:"contained,omitempty" json:"contained,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// Canonical identifier for this subscription topic, represented as an absolute URI (globally unique)
	Url custom.URI `bson:"url" json:"url"`
	// Business identifier for subscription topic
	Identifier []Identifier `bson:"identifier,omitempty" json:"identifier,omitempty"`
	// Business version of the subscription topic
	Version *string `bson:"version,omitempty" json:"version,omitempty"`
	// How to compare versions
	VersionAlgorithm *string `bson:"versionAlgorithm,omitempty" json:"versionAlgorithm,omitempty"`
	// Name for this subscription topic (computer friendly)
	Name *string `bson:"name,omitempty" json:"name,omitempty"`
	// Name for this subscription topic (human friendly)
	Title *string `bson:"title,omitempty" json:"title,omitempty"`
	// Based on FHIR protocol or definition
	DerivedFrom []custom.Canonical[SubscriptionTopic] `bson:"derivedFrom,omitempty" json:"derivedFrom,omitempty"`
	// draft | active | retired | unknown
	Status custom.Code `bson:"status" json:"status"`
	// If for testing purposes, not real usage
	Experimental *bool `bson:"experimental,omitempty" json:"experimental,omitempty"`
	// Date status first applied
	Date *custom.DateTime `bson:"date,omitempty" json:"date,omitempty"`
	// The name of the individual or organization that published the SubscriptionTopic
	Publisher *string `bson:"publisher,omitempty" json:"publisher,omitempty"`
	// Contact details for the publisher
	Contact []ContactDetail `bson:"contact,omitempty" json:"contact,omitempty"`
	// Natural language description of the SubscriptionTopic
	Description *custom.Markdown `bson:"description,omitempty" json:"description,omitempty"`
	// Content intends to support these contexts
	UseContext []UsageContext `bson:"useContext,omitempty" json:"useContext,omitempty"`
	// Intended jurisdiction of the SubscriptionTopic (if applicable)
	Jurisdiction []CodeableConcept `bson:"jurisdiction,omitempty" json:"jurisdiction,omitempty"`
	// Why this SubscriptionTopic is defined
	Purpose *custom.Markdown `bson:"purpose,omitempty" json:"purpose,omitempty"`
	// Use and/or publishing restrictions
	Copyright *custom.Markdown `bson:"copyright,omitempty" json:"copyright,omitempty"`
	// Copyright holder and year(s)
	CopyrightLabel *string `bson:"copyrightLabel,omitempty" json:"copyrightLabel,omitempty"`
	// When SubscriptionTopic is/was approved by publisher
	ApprovalDate *custom.Date `bson:"approvalDate,omitempty" json:"approvalDate,omitempty"`
	// Date the Subscription Topic was last reviewed by the publisher
	LastReviewDate *custom.Date `bson:"lastReviewDate,omitempty" json:"lastReviewDate,omitempty"`
	// The effective date range for the SubscriptionTopic
	EffectivePeriod *Period `bson:"effectivePeriod,omitempty" json:"effectivePeriod,omitempty"`
	// Definition of a resource-based trigger for the subscription topic
	ResourceTrigger []SubscriptionTopicResourceTrigger `bson:"resourceTrigger,omitempty" json:"resourceTrigger,omitempty"`
	// Event definitions the SubscriptionTopic
	EventTrigger []SubscriptionTopicEventTrigger `bson:"eventTrigger,omitempty" json:"eventTrigger,omitempty"`
	// Properties by which a Subscription can filter notifications from the SubscriptionTopic
	CanFilterBy []SubscriptionTopicCanFilterBy `bson:"canFilterBy,omitempty" json:"canFilterBy,omitempty"`
	// Properties for describing the shape of notifications generated by this topic
	NotificationShape []SubscriptionTopicNotificationShape `bson:"notificationShape,omitempty" json:"notificationShape,omitempty"`
}

type SubscriptionTopicResourceTrigger struct {
	// Unique id for inter-element referencing
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// Text representation of the resource trigger
	Description *custom.Markdown `bson:"description,omitempty" json:"description,omitempty"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource custom.URI `bson:"resource" json:"resource"`
	// create | update | delete
	SupportedInteraction []custom.Code `bson:"supportedInteraction,omitempty" json:"supportedInteraction,omitempty"`
	// Query based trigger rule
	QueryCriteria *SubscriptionTopicResourceTriggerQueryCriteria `bson:"queryCriteria,omitempty" json:"queryCriteria,omitempty"`
	// FHIRPath based trigger rule
	FhirPathCriteria *string `bson:"fhirPathCriteria,omitempty" json:"fhirPathCriteria,omitempty"`
}

type SubscriptionTopicResourceTriggerQueryCriteria struct {
	// Unique id for inter-element referencing
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// Rule applied to previous resource state
	Previous *string `bson:"previous,omitempty" json:"previous,omitempty"`
	// test-passes | test-fails
	ResultForCreate *custom.Code `bson:"resultForCreate,omitempty" json:"resultForCreate,omitempty"`
	// Rule applied to current resource state
	Current *string `bson:"current,omitempty" json:"current,omitempty"`
	// test-passes | test-fails
	ResultForDelete *custom.Code `bson:"resultForDelete,omitempty" json:"resultForDelete,omitempty"`
	// Both must be true flag
	RequireBoth *bool `bson:"requireBoth,omitempty" json:"requireBoth,omitempty"`
}

type SubscriptionTopicEventTrigger struct {
	// Unique id for inter-element referencing
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// Text representation of the event trigger
	Description *custom.Markdown `bson:"description,omitempty" json:"description,omitempty"`
	// Event which can trigger a notification from the SubscriptionTopic
	Event CodeableConcept `bson:"event" json:"event"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource custom.URI `bson:"resource" json:"resource"`
}

type SubscriptionTopicCanFilterBy struct {
	// Unique id for inter-element referencing
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// Description of this filter parameter
	Description *custom.Markdown `bson:"description,omitempty" json:"description,omitempty"`
	// URL of the triggering Resource that this filter applies to
	Resource *custom.URI `bson:"resource,omitempty" json:"resource,omitempty"`
	// Human-readable and computation-friendly name for a filter parameter usable by subscriptions on this topic, via Subscription.filterBy.filterParameter
	FilterParameter string `bson:"filterParameter" json:"filterParameter"`
	// Canonical URL for a filterParameter definition
	FilterDefinition *custom.URI `bson:"filterDefinition,omitempty" json:"filterDefinition,omitempty"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator []custom.Code `bson:"comparator,omitempty" json:"comparator,omitempty"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | of-type | code-text | text-advanced | iterate
	Modifier []custom.Code `bson:"modifier,omitempty" json:"modifier,omitempty"`
}

type SubscriptionTopicNotificationShape struct {
	// Unique id for inter-element referencing
	Id *string `bson:"id,omitempty" json:"id,omitempty"`
	// Additional content defined by implementations
	Extension []Extension `bson:"extension,omitempty" json:"extension,omitempty"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `bson:"modifierExtension,omitempty" json:"modifierExtension,omitempty"`
	// URL of the Resource that is the focus (main) resource in a notification shape
	Resource custom.URI `bson:"resource" json:"resource"`
	// Include directives, rooted in the resource for this shape
	Include []string `bson:"include,omitempty" json:"include,omitempty"`
	// Reverse include directives, rooted in the resource for this shape
	RevInclude []string `bson:"revInclude,omitempty" json:"revInclude,omitempty"`
}

func (s SubscriptionTopic) ResourceType() string {
	return "StructureDefinition"
}
