// GENERATED CODE – DO NOT EDIT!

package valuesets

/*
Composed of following code systems:
- http://hl7.org/fhir/bundle-type
*/type BundleType string

const (
	// The bundle is a document. The first resource is a Composition.
	BundleTypeDocument BundleType = "document"
	// The bundle is a message. The first resource is a MessageHeader.
	BundleTypeMessage BundleType = "message"
	// The bundle is a transaction - intended to be processed by a server as an atomic commit.
	BundleTypeTransaction BundleType = "transaction"
	// The bundle is a transaction response. Because the response is a transaction response, the transaction has succeeded, and all responses are error free.
	BundleTypeTransactionResponse BundleType = "transaction-response"
	// The bundle is a set of actions - intended to be processed by a server as a group of independent actions.
	BundleTypeBatch BundleType = "batch"
	// The bundle is a batch response. Note that as a batch, some responses may indicate failure and others success.
	BundleTypeBatchResponse BundleType = "batch-response"
	// The bundle is a list of resources from a history interaction on a server.
	BundleTypeHistory BundleType = "history"
	// The bundle is a list of resources returned as a result of a search/query interaction, operation, or message.
	BundleTypeSearchset BundleType = "searchset"
	// The bundle is a set of resources collected into a single package for ease of distribution that imposes no processing obligations or behavioral rules beyond persistence.
	BundleTypeCollection BundleType = "collection"
	// The bundle has been generated by a Subscription to communicate information to a client.
	BundleTypeSubscriptionNotification BundleType = "subscription-notification"
)
