// GENERATED CODE – DO NOT EDIT!

package valuesets

/*
Composed of following code systems:
- http://hl7.org/fhir/document-relationship-type
*/type DocumentRelationshipType string

const (
	// This document logically replaces or supersedes the target document.
	DocumentRelationshipTypeReplaces DocumentRelationshipType = "replaces"
	// This document was generated by transforming the target document (e.g. format or language conversion).
	DocumentRelationshipTypeTransforms DocumentRelationshipType = "transforms"
	// This document is a signature of the target document.
	DocumentRelationshipTypeSigns DocumentRelationshipType = "signs"
	// This document adds additional information to the target document.
	DocumentRelationshipTypeAppends DocumentRelationshipType = "appends"
	// This document embeds the content from the (source) target document.
	DocumentRelationshipTypeIncorporates DocumentRelationshipType = "incorporates"
	// This document summarizes the content from the (source) target document.
	DocumentRelationshipTypeSummarizes DocumentRelationshipType = "summarizes"
)
