// GENERATED CODE – DO NOT EDIT!

package valuesets

/*
Composed of following code systems:
- http://hl7.org/fhir/genomicstudy-methodtype
*/type GenomicStudyMethodType string

const (
	GenomicStudyMethodTypeBiochemicalGenetics                              GenomicStudyMethodType = "biochemical-genetics"
	GenomicStudyMethodTypeCytogenetics                                     GenomicStudyMethodType = "cytogenetics"
	GenomicStudyMethodTypeMolecularGenetics                                GenomicStudyMethodType = "molecular-genetics"
	GenomicStudyMethodTypeAnalyte                                          GenomicStudyMethodType = "analyte"
	GenomicStudyMethodTypeChromosomeBreakageStudies                        GenomicStudyMethodType = "chromosome-breakage-studies"
	GenomicStudyMethodTypeDeletionDuplicationAnalysis                      GenomicStudyMethodType = "deletion-duplication-analysis"
	GenomicStudyMethodTypeDetectionOfHomozygosity                          GenomicStudyMethodType = "detection-of-homozygosity"
	GenomicStudyMethodTypeEnzymeAssay                                      GenomicStudyMethodType = "enzyme-assay"
	GenomicStudyMethodTypeFishInterphase                                   GenomicStudyMethodType = "fish-interphase"
	GenomicStudyMethodTypeFishMetaphase                                    GenomicStudyMethodType = "fish-metaphase"
	GenomicStudyMethodTypeFlowCytometry                                    GenomicStudyMethodType = "flow-cytometry"
	GenomicStudyMethodTypeFish                                             GenomicStudyMethodType = "fish"
	GenomicStudyMethodTypeImmunohistochemistry                             GenomicStudyMethodType = "immunohistochemistry"
	GenomicStudyMethodTypeKaryotyping                                      GenomicStudyMethodType = "karyotyping"
	GenomicStudyMethodTypeLinkageAnalysis                                  GenomicStudyMethodType = "linkage-analysis"
	GenomicStudyMethodTypeMethylationAnalysis                              GenomicStudyMethodType = "methylation-analysis"
	GenomicStudyMethodTypeMsi                                              GenomicStudyMethodType = "msi"
	GenomicStudyMethodTypeMulticolorFishmfish                              GenomicStudyMethodType = "m-fish"
	GenomicStudyMethodTypeMutationScanningOfSelectExons                    GenomicStudyMethodType = "mutation-scanning-of-select-exons"
	GenomicStudyMethodTypeMutationScanningOfTheEntireCodingRegion          GenomicStudyMethodType = "mutation-scanning-of-the-entire-coding-region"
	GenomicStudyMethodTypeProteinAnalysis                                  GenomicStudyMethodType = "protein-analysis"
	GenomicStudyMethodTypeProteinExpression                                GenomicStudyMethodType = "protein-expression"
	GenomicStudyMethodTypeRnaAnalysis                                      GenomicStudyMethodType = "rna-analysis"
	GenomicStudyMethodTypeSequenceAnalysisOfSelectExons                    GenomicStudyMethodType = "sequence-analysis-of-select-exons"
	GenomicStudyMethodTypeSequenceAnalysisOfTheEntireCodingRegion          GenomicStudyMethodType = "sequence-analysis-of-the-entire-coding-region"
	GenomicStudyMethodTypeSisterChromatidExchange                          GenomicStudyMethodType = "sister-chromatid-exchange"
	GenomicStudyMethodTypeTargetedVariantAnalysis                          GenomicStudyMethodType = "targeted-variant-analysis"
	GenomicStudyMethodTypeUdp                                              GenomicStudyMethodType = "udp"
	GenomicStudyMethodTypeAspe                                             GenomicStudyMethodType = "aspe"
	GenomicStudyMethodTypeAlternativeSplicingDetection                     GenomicStudyMethodType = "alternative-splicing-detection"
	GenomicStudyMethodTypeBiDirectionalSangerSequenceAnalysis              GenomicStudyMethodType = "bi-directional-sanger-sequence-analysis"
	GenomicStudyMethodTypeCBanding                                         GenomicStudyMethodType = "c-banding"
	GenomicStudyMethodTypeCia                                              GenomicStudyMethodType = "cia"
	GenomicStudyMethodTypeChromatinImmunoprecipitationOnChIp               GenomicStudyMethodType = "chromatin-immunoprecipitation-on-chip"
	GenomicStudyMethodTypeComparativeGenomicHybridization                  GenomicStudyMethodType = "comparative-genomic-hybridization"
	GenomicStudyMethodTypeDamid                                            GenomicStudyMethodType = "damid"
	GenomicStudyMethodTypeDigitalVirtualKaryotyping                        GenomicStudyMethodType = "digital-virtual-karyotyping"
	GenomicStudyMethodTypeDigitalMicrofluidicMicrospheres                  GenomicStudyMethodType = "digital-microfluidic-microspheres"
	GenomicStudyMethodTypeEnzymaticLevels                                  GenomicStudyMethodType = "enzymatic-levels"
	GenomicStudyMethodTypeEnzymeActivity                                   GenomicStudyMethodType = "enzyme-activity"
	GenomicStudyMethodTypeElisa                                            GenomicStudyMethodType = "elisa"
	GenomicStudyMethodTypeFluorometry                                      GenomicStudyMethodType = "fluorometry"
	GenomicStudyMethodTypeFusionGenesMicroarrays                           GenomicStudyMethodType = "fusion-genes-microarrays"
	GenomicStudyMethodTypeGBanding                                         GenomicStudyMethodType = "g-banding"
	GenomicStudyMethodTypeGasChromatographyMassSpectrometryGcms            GenomicStudyMethodType = "gc-ms"
	GenomicStudyMethodTypeGeneExpressionProfiling                          GenomicStudyMethodType = "gene-expression-profiling"
	GenomicStudyMethodTypeGeneId                                           GenomicStudyMethodType = "gene-id"
	GenomicStudyMethodTypeGoldNanoparticleProbeTechnology                  GenomicStudyMethodType = "gold-nanoparticle-probe-technology"
	GenomicStudyMethodTypeHplc                                             GenomicStudyMethodType = "hplc"
	GenomicStudyMethodTypeLiquidChromatographyMassSpectrometryLcms         GenomicStudyMethodType = "lc-ms"
	GenomicStudyMethodTypeLiquidChromatographyTandemMassSpectrometryLcmsms GenomicStudyMethodType = "lc-ms-ms"
	GenomicStudyMethodTypeMetaboliteLevels                                 GenomicStudyMethodType = "metabolite-levels"
	GenomicStudyMethodTypeMethylationSpecificPcr                           GenomicStudyMethodType = "methylation-specific-pcr"
	GenomicStudyMethodTypeMicroarray                                       GenomicStudyMethodType = "microarray"
	GenomicStudyMethodTypeMlpa                                             GenomicStudyMethodType = "mlpa"
	GenomicStudyMethodTypeNextGenerationNgsMassivelyParallelSequencingMps  GenomicStudyMethodType = "ngs-mps"
	GenomicStudyMethodTypeOla                                              GenomicStudyMethodType = "ola"
	GenomicStudyMethodTypeOligonucleotideHybridizationBasedDnaSequencing   GenomicStudyMethodType = "oligonucleotide-hybridization-based-dna-sequencing"
	GenomicStudyMethodTypeOther                                            GenomicStudyMethodType = "other"
	GenomicStudyMethodTypePcr                                              GenomicStudyMethodType = "pcr"
	GenomicStudyMethodTypePcrWithAlleleSpecificHybridization               GenomicStudyMethodType = "pcr-with-allele-specific-hybridization"
	GenomicStudyMethodTypePcrrflpWithSouthernHybridization                 GenomicStudyMethodType = "pcr-rflp-with-southern-hybridization"
	GenomicStudyMethodTypeProteinTruncationTest                            GenomicStudyMethodType = "protein-truncation-test"
	GenomicStudyMethodTypePyrosequencing                                   GenomicStudyMethodType = "pyrosequencing"
	GenomicStudyMethodTypeQBanding                                         GenomicStudyMethodType = "q-banding"
	GenomicStudyMethodTypeQpcr                                             GenomicStudyMethodType = "qpcr"
	GenomicStudyMethodTypeRBanding                                         GenomicStudyMethodType = "r-banding"
	GenomicStudyMethodTypeRflp                                             GenomicStudyMethodType = "rflp"
	GenomicStudyMethodTypeRtlamp                                           GenomicStudyMethodType = "rt-lamp"
	GenomicStudyMethodTypeRtpcr                                            GenomicStudyMethodType = "rt-pcr"
	GenomicStudyMethodTypeRtpcrWithGelAnalysis                             GenomicStudyMethodType = "rt-pcr-with-gel-analysis"
	GenomicStudyMethodTypeRtqpcr                                           GenomicStudyMethodType = "rt-qpcr"
	GenomicStudyMethodTypeSnpDetection                                     GenomicStudyMethodType = "snp-detection"
	GenomicStudyMethodTypeSilverStaining                                   GenomicStudyMethodType = "silver-staining"
	GenomicStudyMethodTypeSky                                              GenomicStudyMethodType = "sky"
	GenomicStudyMethodTypeTBanding                                         GenomicStudyMethodType = "t-banding"
	GenomicStudyMethodTypeTandemMassSpectrometryMsms                       GenomicStudyMethodType = "ms-ms"
	GenomicStudyMethodTypeTetraNucleotideRepeatByPcrOrSouthernBlot         GenomicStudyMethodType = "tetra-nucleotide-repeat-by-pcr-or-southern-blot"
	GenomicStudyMethodTypeTilingArrays                                     GenomicStudyMethodType = "tiling-arrays"
	GenomicStudyMethodTypeTrinucleotideRepeatByPcrOrSouthernBlot           GenomicStudyMethodType = "trinucleotide-repeat-by-pcr-or-southern-blot"
	GenomicStudyMethodTypeUniDirectionalSangerSequencing                   GenomicStudyMethodType = "uni-directional-sanger-sequencing"
)
