// GENERATED CODE – DO NOT EDIT!

package valuesets

/*
Composed of following code systems:
- http://hl7.org/fhir/report-relation-type
*/type ReportRelationshipType string

const (
	// This document replaces or supersedes the target document.
	ReportRelationshipTypeReplaces ReportRelationshipType = "replaces"
	// This document notes corrections or changes to replace or supersede parts of the target document.
	ReportRelationshipTypeAmends ReportRelationshipType = "amends"
	// This document adds additional information to the target document.
	ReportRelationshipTypeAppends ReportRelationshipType = "appends"
	// This document was generated by transforming the target document (eg format or language conversion).
	ReportRelationshipTypeTransforms ReportRelationshipType = "transforms"
	// This document was.
	ReportRelationshipTypeReplacedWith ReportRelationshipType = "replacedWith"
	// This document was.
	ReportRelationshipTypeAmendedWith ReportRelationshipType = "amendedWith"
	// This document was.
	ReportRelationshipTypeAppendedWith ReportRelationshipType = "appendedWith"
	// This document was.
	ReportRelationshipTypeTransformedWith ReportRelationshipType = "transformedWith"
)
