// GENERATED CODE – DO NOT EDIT!

package valuesets

/*
Composed of following code systems:
- http://hl7.org/fhir/map-target-list-mode
*/type StructureMapTargetListMode string

const (
	// when the target list is being assembled, the items for this rule go first. If more than one rule defines a first item (for a given instance of mapping) then this is an error.
	StructureMapTargetListModeFirst StructureMapTargetListMode = "first"
	// the target instance is shared with the target instances generated by another rule (up to the first common n items, then create new ones).
	StructureMapTargetListModeShare StructureMapTargetListMode = "share"
	// when the target list is being assembled, the items for this rule go last. If more than one rule defines a last item (for a given instance of mapping) then this is an error.
	StructureMapTargetListModeLast StructureMapTargetListMode = "last"
	// the target instance is shared with a number of target instances generated by another rule (up to the first common n items, then create new ones).
	StructureMapTargetListModeSingle StructureMapTargetListMode = "single"
)
